name: "Sumesh Chakkaravarthi"
tagline: "Transforming complex data into actionable insights."
email: "sumeshchakkaravarthi@gmail.com"
phone: "857-351-9440"
location: "Boston, MA"
github: "https://github.com/sumesh-chakkaravarthi"
linkedin: "https://linkedin.com/in/sumesh-chakkaravarthi"
badge: "DATA SCIENTIST • ML ENGINEER"
